version: '3.8'
services:
  resume_doctor: # Updated service name
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000 # Replace with desired port(s) if needed
    networks:
      - mynetwork
networks:
  mynetwork:

